        <?php require('templates/header.phtml'); ?>
        <table>
           <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Edad</th>
                <th>Club</th>
                </tr>
                <tr> 
                <td><?php echo $jugador->nombre ?> </td>
                <td> <?php echo $jugador->apellido ?> </td>
                <td> <?php echo $jugador->edad ?> </td>
                <td> <?php echo $jugador->club ?> </td>
                </tr>
                <link rel="stylesheet" href="style.css">
        </table>
        